apiVersion: skaffold/v2beta22
kind: Config
deploy: # start and stops k8s objects (such as deploymebts and services)
  kubectl:
    manifests:
      - ./skaffold_test/*
build: # build and sync images
  local:
    push: false
  artifacts:
    - image: service-template-k8s-dev.image
      context: ../services/service_template 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .



# skaffold supposed to:
# a. lunch and shut down the deployments, services, and the rest of k8s objects.   
# b. build the images in case it dont exist
# c. listen on file changes and sync injecting or rebuild and restart



