apiVersion: skaffold/v2beta28
kind: Config
deploy: # start and stops k8s objects (such as deploymebts and services)
  kubectl:
    manifests:
      - ./objects/*
build: # build and sync images
  # local:
  #   push: false
  googleCloudBuild:
    projectId: chatmate-354718
  artifacts:
    - image: gcr.io/chatmate-354718/service_template
      context: ../services/service_template 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .



# skaffold supposed to:
# a. lunch and shut down the deployments, services, and the rest of k8s objects.   
# b. build the images in case it dont exist
# c. listen on file changes and sync injecting or rebuild and restart



